# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Webb Lab(b)
tagline:          'CSU'
description:      'Modeling ecology and evolution'
url:              
baseurl:          /

author:
  name:           'Clint Leach'
  url:            clint-leach.github.io

paginate:         5


github:
  repo:           https://github.com/webblabb/webblabb.github.io

collections:
- people
- publications
